function replica_db_login_copy --description 'Copies the auth token generated by replica_db_login. For authenticating in SequelAce.'
    # Copies the output of replica_db_login
    replica_db_login | pbcopy
    echo "Auth token copied"
end
